# fly.toml app configuration file generated for morning-silence-6173 on 2023-05-22T23:17:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morning-silence-6173"
primary_region = "yyz"
[env]
  PORT = 3000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
